# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{autotest-stumpwm}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yoshinori Tahara"]
  s.date = %q{2010-01-15}
  s.description = %q{autotest の結果を Stumpwm で表示します。autotest-growl にどっぷり依存してます。}
  s.email = %q{read.eval.print@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "autotest-stumpwm.gemspec",
     "lib/autotest-stumpwm.rb",
     "lib/autotest/stumpwm.rb",
     "spec/autotest-stumpwm_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/quek/autotest-stumpwm}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{autotest の結果を Stumpwm で表示します。}
  s.test_files = [
    "spec/autotest-stumpwm_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<autotest-growl>, [">= 0.1.7"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<autotest-growl>, [">= 0.1.7"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<autotest-growl>, [">= 0.1.7"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

